### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by vv01f** [RadicalMilitantLibrary/manual#11]
right now and with each change online again the manual release (PDF, ODT, EPUB, …) deployed on the library is outdated; for users it is maybe not easy to get a build running themselves and pulling in a version once (like authors and devs) in a while someone has to take care of this; but those want it to be as easy as possible after putting all the tools on their machines => automation likely helps in the long term

### problems:

1. needs build system somewhere maintained
2. changes might need approval so not every change is pulled on site
3. no revision number with `git`, just a chaos of sha1 and metadata

### solutions

0. circumvent and just display markdown version nicely online, e.g. [with a php parser](https://github.com/RadicalMilitantLibrary/www/issues/48)
1. well, can be done either locally or on a server or a VM if isolation is intended; server solutions both might be hosted separately but best reachable via tor
2. tagging on a revision we (see problem 3)
3.  `git` enables us to have a commit hash instead of an ever growing revision number (formerly used with `svn`), this one can collide, so it is better to refer to a date-time combined and tag the manual on a "version" with a tool to automatically build a certain release.

### todo

* just go for solution 0

or (optional)

* [ ] enable a revision number like thing; [see approaches](http://stackoverflow.com/questions/4120001/)
* [ ] implement revision system
* [ ] enable it best for Makefile syntax
* [ ] output revision number when built successful
* [ ] output help on tagging with git for the revision number
* [ ] `make rev = 123` => call make for the revision 123 (s.a. [Overriding in make manual](https://www.gnu.org/software/make/manual/make.html#Overriding))

**Comment by ewa4boeker** [comment]
nice approach, but overkill for the manual here.
if anyone has it running it might still be used, just no importance to it.
